// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://fvqmzthtpanjxnuszezq.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6ImZ2cW16dGh0cGFuanhudXN6ZXpxIiwicm9sZSI6ImFub24iLCJpYXQiOjE3NTMzOTc0NjcsImV4cCI6MjA2ODk3MzQ2N30.nZdCj-LnkI7xc8lGa8vfscZ8pLo4Cer3wW5qPMvos9M";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY, {
  auth: {
    storage: localStorage,
    persistSession: true,
    autoRefreshToken: true,
  }
});